import 'package:flutter/material.dart';
import 'package:hello_flutter_world/widgets/screens/autogenerated_words.dart';

class Navigation extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    void _navigateToAutoGenerated_Words() {
      Navigator.of(context).push(MaterialPageRoute(builder: (_) {
        return AutoGeneratedWords();
      }));
    }

    Widget _buildNavigation() {
      return ListView.builder(itemBuilder: (contaxt, i) {
        return ListTile(title: Text('Eco'));
      });
    }

    return Scaffold(
      appBar: AppBar(
        title: Text('Testing Site'),
      ),
      body: _buildNavigation(),
    );
  }
}
